import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

MODELS_DIR = BASE_DIR / "models"
DATA_DIR = BASE_DIR / "data"
OUTPUT_DIR = BASE_DIR / "output"

HEADSET_MODEL_PATH = MODELS_DIR / "headsetmodel.pt"
PHONE_MODEL_PATH = MODELS_DIR / "pdfinal.pt"
FACE_ENCODINGS_PATH = MODELS_DIR / "face_encodings.pickle"

LIP_DISTANCE_THRESHOLD = 0.05
EAR_THRESHOLD = 0.2
CONSECUTIVE_FRAMES = 5

DETECTION_CONFIDENCE = 0.5
TRACKING_CONFIDENCE = 0.5
MAX_NUM_FACES = 1

TARGET_WIDTH = 640
TARGET_HEIGHT = 480

LEFT_EYE = [362, 385, 387, 263, 373, 380]
RIGHT_EYE = [33, 160, 158, 133, 153, 144]
LIPS = [13, 14]

ALERT_PHONE_FRAMES = 30
ALERT_HEADSET_FRAMES = 30
ALERT_DROWSY_FRAMES = 5

VIDEO_CODEC = 'mp4v'